# Generated by Django 4.0.3 on 2022-03-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emaill',
            field=models.EmailField(default='A', max_length=254),
        ),
    ]
