# Generated by Django 4.0.3 on 2022-03-29 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_emaill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='emaill',
            new_name='email',
        ),
    ]
