# Generated by Django 4.0.3 on 2022-04-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_first_name_profile_name_profile_phone2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
