# Generated by Django 4.0.3 on 2022-05-01 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_form_product_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffsetForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('management', models.CharField(max_length=100)),
                ('media_address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('landline', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('mterial', models.CharField(max_length=100)),
                ('information', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='form',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.AddField(
            model_name='offsetform',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
