# Generated by Django 4.0.3 on 2022-05-01 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_offsetform_remove_product_form_delete_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offsetform',
            name='product',
        ),
        migrations.AddField(
            model_name='offsetform',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
