# Generated by Django 4.0.3 on 2022-05-01 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_offsetform_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
