# Generated by Django 4.0.3 on 2022-05-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_form_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='order'),
        ),
        migrations.AddField(
            model_name='form',
            name='length',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='form',
            name='width',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
