# Generated by Django 4.0.3 on 2022-05-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_forms_remove_sublimitionform_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
