# Generated by Django 4.0.3 on 2022-05-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_offsetform_sublimitionform_delete_forms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sublimitionform',
            old_name='mterial',
            new_name='material',
        ),
    ]
