# Generated by Django 4.0.3 on 2022-05-06 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_mterial_sublimitionform_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offsetform',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sublimitionform',
            name='category',
        ),
        migrations.AddField(
            model_name='offsetform',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
        migrations.AddField(
            model_name='sublimitionform',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
