# Generated by Django 4.0.3 on 2022-05-07 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_forms_remove_sublimitionform_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffsetForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('management', models.CharField(max_length=100)),
                ('media_address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('landline', models.CharField(max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='SublimitionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('material', models.CharField(max_length=100)),
                ('information', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='order')),
                ('length', models.PositiveIntegerField(default=10)),
                ('width', models.PositiveIntegerField(default=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='form',
        ),
        migrations.DeleteModel(
            name='forms',
        ),
    ]
