# Generated by Django 4.0.3 on 2022-05-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_sublimitionform_category_delete_offsetform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='offsetForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('management', models.CharField(max_length=100)),
                ('media_address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('landline', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sublimitionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('material', models.CharField(max_length=100)),
                ('information', models.TextField()),
                ('length', models.PositiveIntegerField(default=10)),
                ('width', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
