# Generated by Django 4.0.3 on 2022-05-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_offsetform_sublimitionform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublimitionform',
            name='length',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='sublimitionform',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sublimitionform',
            name='width',
            field=models.PositiveIntegerField(),
        ),
    ]
