# Generated by Django 4.0.3 on 2022-05-09 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_sublimitionform_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('management', models.CharField(max_length=100)),
                ('media_address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('landline', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('material', models.CharField(max_length=100)),
                ('information', models.TextField()),
                ('length', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='offsetForm',
        ),
        migrations.DeleteModel(
            name='sublimitionForm',
        ),
        migrations.AddField(
            model_name='product',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.forms'),
        ),
    ]
