# Generated by Django 4.0.3 on 2022-05-09 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_forms_delete_offsetform_delete_sublimitionform_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='form',
        ),
        migrations.AddField(
            model_name='forms',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product'),
        ),
    ]
