# Generated by Django 4.0.3 on 2022-05-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_forms_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='information',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='job',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='forms',
            name='management',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='forms',
            name='material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='forms',
            name='media_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
