# Generated by Django 4.0.3 on 2022-05-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_forms_landline_alter_forms_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='create',
        ),
        migrations.RemoveField(
            model_name='product',
            name='extra_information',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='update',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
